[package]
name = "client"
version = "0.1.0"
authors = ["Softbear, Inc."]
edition = "2018"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = {version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
serde = "1.0"
serde_json = "1.0"
serde-wasm-bindgen = "0.3"
glam = {version="0.18", features=["scalar-math"]}
common = {path="../common", features=["js"]}
instant = { version = "0.1.10", features = [ "wasm-bindgen" ] }
rand = "0.8"
core_protocol = {path="../core/core_protocol"}
client_util = {path="../core/client_util"}
arrayvec = "0.7"
sprite_sheet = {path="../sprite_sheet"}
itertools = "0.10"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'AudioContext',
    'AudioBuffer',
    'AudioParam',
    'AudioDestinationNode',
    'AudioBufferSourceNode',
    'AudioContextState',
    'GainNode',
    'BinaryType',
    'Blob',
    'CanvasRenderingContext2d',
    'CloseEvent',
    'Document',
    'Element',
    'ErrorEvent',
    'FileReader',
    'HtmlCanvasElement',
    'HtmlImageElement',
    'KeyboardEvent',
    'Location',
    'MessageEvent',
    'MouseEvent',
    'OesVertexArrayObject',
    'OesStandardDerivatives',
    'ProgressEvent',
    'TextMetrics',
    'WebGlBuffer',
    'WebGlProgram',
    'WebGlRenderingContext',
    'WebGlShader',
    'WebGlTexture',
    'WebGlUniformLocation',
    'WebGlVertexArrayObject',
    'WebSocket',
    'Window',
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
]
