version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server_main/Dockerfile
    ports:
      - "8192:8192"
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    depends_on:
      - server
