[package]
name = "yew_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew_icons = {version = "0", features = ["FontAwesomeSolidSquareCaretLeft", "FontAwesomeSolidSquareCaretRight"]}
gloo-events = "0.1"
wasm-bindgen = "0.2"
core_protocol = {path = "../core_protocol"}
client_util = {path = "../client_util"}
serde = "1.0"
gloo-render = "0.1"
stylist = {version = "0.10", features = ["yew_integration"]}

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Location',
    'UiEvent',
    'Window',
]
