[package]
name = "server"
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[profile.release.package."*"]
debug = false

[patch.crates-io]
#actix-http = { git = "https://github.com/actix/actix-web"}
#actix-tls = { git = "https://github.com/actix/actix-net", branch = "fix/tls-handshake-timeout" }

# An attempt to speed up user agent regex compilation.
[profile.dev.package.regex]
opt-level = 3

[profile.dev.package.fancy-regex]
opt-level = 3

[profile.dev.package.uaparser]
opt-level = 3

[dependencies]
actix = "0.12"
actix-codec = "0.4.0"
actix-web = {version="4.0.0-beta.9", features=["rustls"]}
actix-web-actors = "4.0.0-beta.7"
actix-files = "0.6.0-beta.7"
actix-plus-static-files = {git="https://github.com/finnbear/actix-plus", branch="actix-web-4"}
#actix-plus-static-files = {path="../../actix-plus/actix-plus-static-files"}
actix-web-middleware-redirect-https = {git="https://github.com/finnbear/actix-web-middleware-redirect-https"}
futures = "0.3.1"
tokio = { version = "1.2" }
glam = { version = "0.18.0", features = ["serde"] }
serde = "1.0.127"
serde_json = "1.0.66"
serde_bytes = "0.11.5"
enum_derive = "0.1.7"
custom_derive = "0.1.7"
atomic_refcell = "0.1.7"
arrayvec = {version = "0.7.1", features = [ "serde" ] }
rand = "0.8.4"
idalloc = "0.1.1"
noise = { version = "0.7.0", default-features = false }
common = {path="../common", version="0.1.0", features=["server"]}
core = {path="../core/core"}
core_protocol = {path="../core/core_protocol"}
servutil = {path="../core/servutil"}
rayon = "1.5.1"
ringbuffer = "0.8.2"
structopt = "0.3.22"
bincode = "1.3.3"
actix-http = "3.0.0-beta.10"
chrono = "0.4.19"
log = {version = "0.4.14", features = [ "release_max_level_info" ] }
env_logger = "0.9.0"
num_cpus = "1"

[dev-dependencies]
image = { version = "0.23.14", features = [ "png" ] }
