[package]
name = "server"
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
actix-http = {git = "https://github.com/actix/actix-web"}
actix-web = {git = "https://github.com/actix/actix-web"}

[profile.release]
debug = true

[profile.release.package."*"]
debug = false

# An attempt to speed up user agent regex compilation.
[profile.dev.package.regex]
opt-level = 3

[profile.dev.package.fancy-regex]
opt-level = 3

[profile.dev.package.uaparser]
opt-level = 3

[dependencies]
actix = "0.12"
actix-codec = "0.4"
actix-web = {version="4.0.0-beta.13", features=["rustls"]}
actix-web-actors = "4.0.0-beta.7"
actix-http = "3.0.0-beta.14"
#actix-http = "3.0.0-beta.13"
#actix-plus-static-files = {path="../../actix-plus/actix-plus-static-files"}
actix-web-middleware-redirect-https = {git="https://github.com/finnbear/actix-web-middleware-redirect-https"}
futures = "0.3"
tokio = { version = "1.2" }
glam = { version = "0.18", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
atomic_refcell = "0.1"
arrayvec = {version = "0.7", features = [ "serde" ] }
rand = "0.8"
idalloc = "0.1"
noise = { version = "0.7", default-features = false }
common = {path="../common", version="0.1", features=["server"]}
core = {path="../core/core"}
core_protocol = {path="../core/core_protocol"}
servutil = {path="../core/servutil"}
rayon = "1.5"
ringbuffer = "0.8"
structopt = "0.3"
log = {version = "0.4", features = [ "release_max_level_info" ] }
env_logger = "0.9"
connection_leak_detector = "0.1.6"
actix-tls = "3.0.0-beta.9"
lazy_static = "1"
lockfree = "0.5"

[dev-dependencies]
image = { version = "0.23.14", features = [ "png" ] }
