[package]
name = "server"
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

[profile.release]
debug = true

[profile.release.package."*"]
debug = false

# An attempt to speed up user agent regex compilation.
[profile.dev.package.regex]
opt-level = 3

[dependencies]
futures = "0.3"
tokio = { version = "1.2" }
glam = { version = "0.18", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
atomic_refcell = "0.1"
arrayvec = {version = "0.7", features = [ "serde" ] }
rand = "0.8"
idalloc = "0.1"
noise = { version = "0.7", default-features = false }
common = {path="../common", version="0.1", features=["server"]}
game_server = {path="../engine/game_server"}
core_protocol = {path="../engine/core_protocol"}
core_server = {path="../engine/core_server"}
server_util = {path="../engine/server_util"}
rayon = "1.5"
ringbuffer = "0.8"
structopt = "0.3"
log = {version = "0.4", features = [ "release_max_level_info" ] }
env_logger = "0.9"
actix-tls = "3.0.0-beta.9"
lazy_static = "1"
rustrict = {version = "0.1", features=["customize"], default-features=false}

[dev-dependencies]
image = { version = "0.23.14", features = [ "png" ] }
