[package]
name = "common"
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

[dependencies]
arrayvec = {version="0.7", features=["serde"]}
actix = {version="0.12", optional = true}
getrandom = "0.2"
rand = "0.8"
glam = {version="0.18", features=["serde"]}
serde = {version="1.0", features=["derive", "rc"]}
serde_json = "1.0"
macros = {path="../macros"}
fast_hilbert = "1.0"
lazy_static = "1.4"
enum-iterator = "0.7"
core_protocol = {path="../engine/core_protocol"}
common_util = {path="../engine/common_util"}
serde_bytes = "0.11"
bincode = "1.3.3"

[features]
server = ["actix"]
js = ["getrandom/js"]

#dev-dependencies]
#criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false