[package]
name = "common"
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

[dependencies]
arrayvec = {version="0.7.1", features=["serde"]}
actix = {version="0.12.0", optional = true}
getrandom = "0.2.3"
rand = "0.8.4"
glam = {version="0.18.0", features=["serde"]}
serde = {version="1.0.127", features=["derive", "rc"]}
serde_json = "1.0.66"
macros = {path="../macros"}
fast_hilbert = "1.0.0"
lazy_static = "1.4.0"
enum-iterator = "0.7.0"
core_protocol = {path="../core/core_protocol"}
serde_bytes = "0.11.5"

[features]
server = ["actix"]
js = ["getrandom/js"]

#dev-dependencies]
#criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false