[package]
name = "sprite_sheet"
version = "0.1.0"
edition = "2018"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

[dependencies]
common = {path="../common"}
serde = "1.0.130"
serde_json = "1.0.67"
glam = "0.18.0"