[package]
name = "renderer3d"
workspace = ".."
version = "0.1.0"
edition = "2021"
authors = ["Softbear, Inc."]
license = "AGPL-3.0-or-later"

[dependencies]
bytemuck = "1.9"
glam = "0.18"
renderer = { path = "../renderer" }
engine_macros = { path = "../engine_macros" }
